name: Integration Testing - Plan

on:
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: Development

    environment: ${{ matrix.environment }}

    steps:
      - name: Microsoft Teams Notifications
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          role-to-assume: ${{ secrets.SOPHOS_DEV_DEPLOY_ROLE }}
          aws-region: us-west-2
          role-session-name: OIDCSession
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.SOPHOS_TF_API_TOKEN }}
      - name: Terraform init
        id: init
        run: |
          REPO="${{ github.repository }}"
          WORKSPACE="${REPO#*/}"

          cat >> remote.tf<<EOF
          terraform {
            backend "remote" {}
          }
          EOF

          cat >> config.remote.tfbackend<<EOF
          hostname = "app.terraform.io"
          organization = "${{ secrets.SOPHOS_TF_ORGANIZATION }}"
          workspaces { name = "$WORKSPACE" }
          EOF

          terraform init -backend-config=config.remote.tfbackend
      - name: Terraform plan
        id: plan
        continue-on-error: true
        run: | 
          terraform plan -input=false -no-color -out=tfplan
        env:
          TF_VAR_console_password: ${{ secrets.CONSOLE_PASSWORD }}
          TF_VAR_config_backup_password: ${{ secrets.CONFIG_BACKUP_PASSWORD }}
          TF_VAR_secure_storage_master_key: ${{ secrets.SECURE_STORAGE_MASTER_KEY }}
          TF_VAR_trusted_ip: ${{ secrets.TRUSTED_IP }}    
      - name: Reformat Plan
        run: |
          echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
          | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt           
      - name: Put plan in github environment variable
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ steps.generate-token.outputs.token }}
          message: |
            ## plan
            ```diff
            + Green
            - Red
            ! Orange
            @@ Pink @@
            #Gray
            ${{ env.PLAN }}     
            ```



          



        
  