name: Terraform lint and auto pull requests

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Lint
      id: lint1
      run: |
        terraform fmt -check -diff
    - name: Terraform fmt list
      if: ${{ failure() }}
      id: lint2
      run: |
        terraform fmt -check -list=true
    - id: diff
      if: ${{ failure() }}
      run: |
        echo '${{ steps.lint1.outputs.stdout || steps.lint1.outputs.stderr }}' \
        | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > diff.txt && \
        echo '${{ steps.lint2.outputs.stdout || steps.lint2.outputs.stderr }}' > list.txt
    - name: Put diff and list in Env Var
      if: ${{ failure() }}
      run: |
        DIFF=$(cat diff.txt)
        echo "DIFF<<EOF" >> $GITHUB_ENV
        echo "$DIFF" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        LIST=$(cat list.txt)
        echo "LIST<<EOF" >> $GITHUB_ENV
        echo "$LIST" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Post Diff to GitHub PR
      uses: mshick/add-pr-comment@v1
      if: ${{ failure() }}
      with:
        allow-repeats: true
        repo-token: ${{ github.token }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ## Terraform Format Diff:
          ```diff
          ${{ env.DIFF }}
          ```

          ## List of files:
          ${{ env.LIST }}
    - name: Post Success to GitHub PR
      uses: mshick/add-pr-comment@v1
      if: ${{ success() }}
      with:
        allow-repeats: true
        repo-token: ${{ github.token }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          :smiley: Linting successful!


  autopr:
    runs-on: ubuntu-latest
    needs: lint
    if: contains('refs/heads/feature', github.ref)
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: autopr
      id: autopr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: dev
        github_token: ${{ github.token }}
        pr_label: |
          autopr
        pr_title: "Pulling ${{ github.ref }} into dev"
        pr_body: ":crown: Automated Pull Request"
        pr_assignee: Dev0psPleb
